name: Deploy-Infra

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

env:
  RESOURCE_GROUP_NAME: ${{ inputs.environment }}-AKS

jobs:
  Infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: bicep
          path: artifacts/bicep/

      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Ensure ${{ env.RESOURCE_GROUP_NAME }}
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          deploymentName: ensure_${{ env.RESOURCE_GROUP_NAME }}
          region: "westeurope"
          template: artifacts/bicep/resourceGroup.bicep
          parameters: "location=westeurope resourceGroupName=${{ env.RESOURCE_GROUP_NAME }}"

      - name: Deploy ${{ env.RESOURCE_GROUP_NAME }}
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          deploymentMode: Complete
          deploymentName: deploy_${{ env.RESOURCE_GROUP_NAME }}
          region: "westeurope"
          template: artifacts/bicep/main.bicep
          parameters: "location=westeurope resourceGroupName=${{ env.RESOURCE_GROUP_NAME }}"
